### ISSUE TITLE
6.3 doesn’t require complexity of sample answer

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-databases#11]
The sample answer for 6.3 has a join to restrict results based on the store, which isn’t necessary for the required output. Perhaps there needs to be more data in order to require this? In any case, the instructions don’t suggest that the store is needed.

**Comment by TomSteeples** [comment]
I have not referenced store data anywhere for Bootcamp 6.  The table is still in the database and may be used in the future.  However it has been removed from the exercises and slides this time.
