### ISSUE TITLE
Exercise 2 questions

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-databases#7]
Exercise states:
>Create a new table in the sandbox schema.
but it isn’t clear what this means—perhaps it should the sequel-mart-schema?

Also, it would be worth being explicit that it’s intended they create the table manually using the UI, as they go on to look at the script for a table in the next step.

**Comment by TomSteeples** [comment]
Exercises have been revamped for Bootcamp 6.  They are designed to be more explicit in what they ask.  I've also removed the requirement for a sandbox schema.  Most of the work will be done directly in the "sequel-mart-schema" with a little bit of input from the generic data schema should one of the exercises not work as planned.
